version: 0.1.{build}

os:
    - Visual Studio 2017

platform:
    - Win32
    - x64

configuration: Debug

environment:
    MSVC_DEFAULT_OPTIONS: ON

init:
    - cmake --version
    - msbuild /version
    - echo %platform%
    - if "%platform%"=="x64" ( set generator="Visual Studio 15 2017 Win64")
    - if "%platform%"=="Win32" ( set generator="Visual Studio 15 2017")
    - echo %generator%

clone_folder: C:\projects\spio
clone_depth: 5

install:
    - git submodule update --init --recursive

before_build:
    - mkdir build
    - cd build
    - cmake -G %generator% -DWERROR=OFF -DCMAKE_BUILD_TYPE=%configuration% ..

build:
    project: C:\projects\spio\build\spio.sln
    parallel: true
    verbosity: normal

test_script:
    - cd %APPVEYOR_BUILD_FOLDER%\tests
    - dir /ad /b /s
    - dir /a-d /b /s
    - ..\build\tests\Debug\tests.exe
    - cd ..
