version: 0.1.{build}

os:
    - Visual Studio 2015
    - Visual Studio 2017

platform:
    - Win32
    - x64

configuration: Release

environment:
    MSVC_DEFAULT_OPTIONS: ON

init:
    - cmake --version
    - msbuild /version
    - echo %platform%
    - set arch=
    - if "%platform"=="x64" ( set arch=" Win64")
    - echo %arch%
    - echo %APPVEYOR_BUILD_WORKER_IMAGE%
    - if "%APPVEYOR_BUILD_WORKER_IMAGE%"=="Visual Studio 2015" ( set generator="Visual Studio 14 2015%arch%" )
    - if "%APPVEYOR_BUILD_WORKER_IMAGE%"=="Visual Studio 2017" ( set generator="Visual Studio 15 2017%arch%" )
    - echo %generator%

clone_folder: C:\projects\spio
clone_depth: 5

install:
    - git submodule update --init --recursive

before_build:
    - mkdir build
    - cd build
    - cmake -G %generator% -DWERROR=OFF -DCMAKE_BUILD_TYPE=%configuration% ..

build:
    project: C:\projects\spio\build\spio.sln
    parallel: true
    verbosity: normal